[package]
name = "tfe"
version = "0.4.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"

[lib]
name = "tfe"
path = "src/lib.rs"
