#!/usr/bin/env python3.6
"""######################################
##########                    ###########
########## Twenty-forty-eight ###########
##########                    ###########
######################################"""

import sys
import time
import argparse
from lib.game import Game
import lib.algorithm as algo


"""##################
#### Manual game ####
##################"""

def manual_game():
    """ Play the 2048 manually """
    # Set keybinds
    keys = {
        "left": "a",
        "right": "d",
        "down": "s",
        "up": "w",
        "quit": "q"
    }
    reversed_keys = {v: k for k, v in keys.items()}

    # While playing games
    while True:

        # Load an empty game and render it
        game = Game()
        rendering.render_manual_in_terminal(keys, game.board.board, game.score, None, game.moves)
        # While not game over
        while True:
            possible_directions = game.possible_directions(game.board.board)
            # Game over if no possible directions
            if len(possible_directions) == 0:
                break

            # Keyboard input (press and release is not working, so we use time.sleep)
            key = read_single_keypress().lower()
            direction = reversed_keys[key] if key in reversed_keys else None

            if direction == "quit":
                sys.exit()

            # Perform a movement
            if direction in possible_directions:
                game.perform_movement(direction)
                # hint = algo.determine_best_movement(game.board.board, possible_directions)
                rendering.render_manual_in_terminal(
                    keys, game.board.board, game.score, direction, game.moves
                )

            # Check if the game has been won
            for row in game.board.board:
                if 2048 in row:
                    #TODO make a fancier print
                    print("\nYou have won the game!!! \n")

        # Game is over, rematch???
        print("\n\n\nGame over!\nFinal score: {}".format(game.score))
        rematch = "."
        while rematch not in ("", "q"):
            rematch = input("Continue (enter) or quit ('q' and enter)?\n")
            rematch = rematch.lower()

        if rematch == "q":
            print("Thanks for playing!")
            break

def read_single_keypress():
    """Waits for a single keypress on stdin.
    #
    This is a silly function to call if you need to do it a lot because it has
    to store stdin's current setup, setup stdin for reading single keystrokes
    then read the single keystroke then revert stdin back after reading the
    keystroke.
    #
    Returns the character of the key that was pressed (zero on
    KeyboardInterrupt which can happen when a signal gets handled)
    #
    Function obtained from:
    https://stackoverflow.com/questions/983354/how-do-i-make-python-wait-for-a-pressed-key
    """
    #
    f_d = sys.stdin.fileno()
    # save old state
    flags_save = fcntl.fcntl(f_d, fcntl.F_GETFL)
    attrs_save = termios.tcgetattr(f_d)
    # make raw - the way to do this comes from the termios(3) man page.
    attrs = list(attrs_save) # copy the stored version to update
    # iflag
    attrs[0] &= ~(termios.IGNBRK | termios.BRKINT | termios.PARMRK
                  | termios.ISTRIP | termios.INLCR | termios. IGNCR
                  | termios.ICRNL | termios.IXON)
    # oflag
    attrs[1] &= ~termios.OPOST
    # cflag
    attrs[2] &= ~(termios.CSIZE | termios. PARENB)
    attrs[2] |= termios.CS8
    # lflag
    attrs[3] &= ~(termios.ECHONL | termios.ECHO | termios.ICANON
                  | termios.ISIG | termios.IEXTEN)
    termios.tcsetattr(f_d, termios.TCSANOW, attrs)
    # turn off non-blocking
    fcntl.fcntl(f_d, fcntl.F_SETFL, flags_save & ~os.O_NONBLOCK)
    # read a single keystroke
    try:
        ret = sys.stdin.read(1) # returns a single character
    except KeyboardInterrupt:
        ret = 0
    finally:
        # restore old state
        termios.tcsetattr(f_d, termios.TCSAFLUSH, attrs_save)
        fcntl.fcntl(f_d, fcntl.F_SETFL, flags_save)
    return ret


"""#####################
#### Automatic game ####
#####################"""

def automatic_game():
    """ Play the 2048 automatically using the ai script """
    # Set time.sleep between frames
    sleeping_time = 0.2

    # Set total games
    total_games = abs(ARGS.total_games)

    # play x games
    game_scores = {}
    games_won = 0
    for game_index in range(1, total_games+1):
        game = Game()

        # Render board if render_game is True
        if ARGS.render:
            rendering.render_automatic_in_terminal(
                game.board.board, game.score, None, game.moves, game_index
            )
            time.sleep(sleeping_time)
        else:
            print(f"Games played: {game_index}/{total_games}", end="\r")

        #Play a single game
        while True:

            # Duplicate the board to determine the possible directions
            possible_directions = game.possible_directions(game.board.board)

            if len(possible_directions) == 0:
                break

            # Let the algorithm choose the best direction to perform
            direction = algo.determine_best_movement(game.board.board, possible_directions)

            # Perform a movement
            game.perform_movement(direction)

            # Render board if render_game is True
            if ARGS.render:
                rendering.render_automatic_in_terminal(
                    game.board.board, game.score, direction, game.moves, game_index
                )
                algo.determine_best_movement(game.board.board, possible_directions, True)
                time.sleep(sleeping_time)

        # Determine if the game has been won
        for row in game.board.board:
            if 2048 in row:
                games_won += 1
                break

        # Save the score of the game
        game_scores[game_index] = game.score

    # Print game output information
    print("\rGames played: {}".format(total_games))
    print("Average score: {}".format(sum(game_scores.values())/total_games))
    print("Highest score: {}".format(game_scores[max(game_scores, key=game_scores.get)]))
    print("The algo has beaten {} games".format(games_won))
    if total_games == 1 and not ARGS.render:
        print("\nTry playing more games using '$ ./main --total_games <any_number_of_games>'")
        print("or see the algorithm play a game using '$ ./main --render True'")


"""############
#### Input ####
############"""

def argument_handler():
    """ handles input arguments """

    parser = argparse.ArgumentParser()
    parser.add_argument(
        "game_mode",
        type=str,
        choices=["manual", "automatic"],
        help="Play the game in manual mode or automatic mode"
    )

    parser.add_argument(
        "--render",
        type=bool,
        choices=[True, False],
        default=False,
        help="Render game in the terminal when running the automatic game (default: False)"
    )

    parser.add_argument(
        "--total_games",
        type=int,
        default=1,
        help="int - The total games that will be played (default: 1)"
    )
    return parser.parse_args()

# Load arguments
ARGS = argument_handler()

if ARGS.game_mode == "manual":
    import os
    import termios
    import fcntl
    import lib.terminal_rendering as rendering

    # Run manual game
    manual_game()

elif ARGS.game_mode == "automatic":
    if ARGS.render:
        import lib.terminal_rendering as rendering

    # Run automatic game
    automatic_game()
