#!/usr/bin/env python3.6
import time
import sys
from lib import curses
from lib.game import Game
screen = curses.Screen()
game = Game()

try:
    moves = 0
    screen.render_game(game.board.board, game.score)
    while (game.game_over() == False):
        key = screen.keypress()
        if (key == 260 and game.left_possible() == True):
            moves = moves + 1
            game.left_move()

        if (key == 261 and game.right_possible() == True):
            moves = moves + 1
            game.right_move()

        if (key == 258 and game.down_possible() == True):
            moves = moves + 1
            game.down_move()

        if (key == 259 and game.up_possible() == True):
            moves = moves + 1
            game.up_move()

        screen.render_game(game.board.board, game.score)
    screen.reset()

except KeyboardInterrupt:
    screen.reset()
    sys.exit()
