#!/usr/bin/env python3 # pylint: disable=C0103
"""The executable script"""

from src.presentation_layer.main_window import run_main_window
from src.data_generator.player import Player


def main():
    """Main script of the program"""

    args = {
        "use_old_games": False,
        "total_games": 10000,
        "fps": 10,
    }

    player = Player()
    player.play_games(args["total_games"], args["use_old_games"])

    run_main_window(args["fps"])


if __name__ == "__main__":
    main()
