#!/usr/bin/env python3 #pylint:disable=invalid-name
"""The executable script"""

from src.presentation_layer.main_window import run_main_window


def main():
    """Main script of the program"""

    args = {
        "fps": 10,
    }

    # player = Player()
    # player.play_games(args["total_games"], args["use_old_games"])
    print("Displaying game data")
    run_main_window(args["fps"])


if __name__ == "__main__":
    main()
