[package]
name = "tfe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stopwatch = "0.0.7"
rand = "0.9.1"
strum = "0.27.1"
strum_macros = "0.27.1"
itertools = "0.14.0"
multimap = "0.10.1"
enum-display = "0.1.3"
mockall = "0.13.1"

[lib]
name = "tfe"
path = "src/lib.rs"

[[bin]]
edition = "2021"
name = "tfe_rust"
path = "src/bin/main.rs"
